//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_CongViec
    {
        public int MaCTCongViec { get; set; }
        public int MaCongViec { get; set; }
        public string NoiDung { get; set; }
        public bool HoanThanh { get; set; }
    
        public virtual CongViec CongViec { get; set; }
    }
}
